trigger:
  branches:
    include: 
    - main
    - master
    - release/*

variables:
- template: variable-templates/general-variables-template.azure-pipelines.yml@tf-pipeline-templates # Template reference
- template: variable-templates/post-pr-azure-variables-template.azure-pipelines.yml@tf-pipeline-templates # Template reference

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: tf-pipeline-templates
    type: git
    name: tf-pipeline-templates

stages:
  - template: post-pr-azure-stages-template.azure-pipelines.yml@tf-pipeline-templates
